/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.form;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author 84934 NguyenThiQuynhGiang
 */
public class Form_Login extends javax.swing.JFrame implements ActionListener, MouseListener{

    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
        addImg();
        jButton_Thoat.addActionListener(this);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Left = new javax.swing.JPanel();
        jLabel_DangNhap = new javax.swing.JLabel();
        jLabel_TenDangNhap = new javax.swing.JLabel();
        jLabel_MatKhau = new javax.swing.JLabel();
        jTextField_TenDangNhap = new javax.swing.JTextField();
        jPasswordField_MatKhau = new javax.swing.JPasswordField();
        jButton_QuenMatKhau = new javax.swing.JButton();
        jButton_DangNhap = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();
        jPanel_Right = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Left.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel_DangNhap.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel_DangNhap.setText("ĐĂNG NHẬP");

        jLabel_TenDangNhap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_TenDangNhap.setText("Tên đăng nhập");

        jLabel_MatKhau.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_MatKhau.setText("Mật khẩu");

        jTextField_TenDangNhap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextField_TenDangNhap.setText("jTextField1");

        jPasswordField_MatKhau.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPasswordField_MatKhau.setText("jPasswordField1");

        jButton_QuenMatKhau.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_QuenMatKhau.setText("Quên mật khẩu");

        jButton_DangNhap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_DangNhap.setText("Đăng nhập");
        jButton_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapActionPerformed(evt);
            }
        });

        jButton_Thoat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ThoatMouseClicked(evt);
            }
        });
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LeftLayout = new javax.swing.GroupLayout(jPanel_Left);
        jPanel_Left.setLayout(jPanel_LeftLayout);
        jPanel_LeftLayout.setHorizontalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftLayout.createSequentialGroup()
                .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_LeftLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_TenDangNhap)
                                .addComponent(jLabel_MatKhau))
                            .addGap(57, 57, 57)
                            .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_TenDangNhap)
                                .addComponent(jPasswordField_MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LeftLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton_QuenMatKhau)))
                    .addGroup(jPanel_LeftLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jButton_Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_LeftLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel_DangNhap)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel_LeftLayout.setVerticalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel_DangNhap)
                .addGap(54, 54, 54)
                .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenDangNhap)
                    .addComponent(jTextField_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MatKhau)
                    .addComponent(jPasswordField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton_QuenMatKhau)
                .addGap(18, 18, 18)
                .addComponent(jButton_DangNhap)
                .addGap(28, 28, 28)
                .addComponent(jButton_Thoat)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel_Right.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel_RightLayout = new javax.swing.GroupLayout(jPanel_Right);
        jPanel_Right.setLayout(jPanel_RightLayout);
        jPanel_RightLayout.setHorizontalGroup(
            jPanel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel_RightLayout.setVerticalGroup(
            jPanel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel_Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DangNhapActionPerformed

    
    private void jButton_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ThoatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ThoatMouseClicked

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    //Event <<chút dô discord nói chi tiết hơn>>
    public void actionPerformed(ActionEvent e) {
       Object o = e.getSource();
       if(o.equals(jButton_Thoat)) {
	    System.exit(0);
	    return;
       }else if(o.equals(jButton_DangNhap)){
         //Có entity mới test được 
       }
                
    }
    //Add image in jPanel_Right
    private void addImg(){
        jPanel_Right = new JPanel();
        ImageIcon img_Login = new ImageIcon("resources/icon/img_LoginWhite.png");// chưa adđ ảnh vào được
        jPanel_Right.add(new JLabel(img_Login));
        add(jPanel_Right, BorderLayout.CENTER);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangNhap;
    private javax.swing.JButton jButton_QuenMatKhau;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JLabel jLabel_DangNhap;
    private javax.swing.JLabel jLabel_MatKhau;
    private javax.swing.JLabel jLabel_TenDangNhap;
    private javax.swing.JPanel jPanel_Left;
    private javax.swing.JPanel jPanel_Right;
    private javax.swing.JPasswordField jPasswordField_MatKhau;
    private javax.swing.JTextField jTextField_TenDangNhap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
}
